services:
  python:
    build:
      context: ./Py
      dockerfile: Dockerfile
    container_name: python
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
    env_file: ./.env
    ports:
      - 5000:5000
      - 8000:8000
    volumes:
      - ./Py:/usr/local/src/api
    init: true
    tty: true
    entrypoint: >
      sh -c "
        cd /usr/local/src/api &&
        uwsgi --ini uwsgi.ini
      "

  mysql:
    image: mysql
    container_name: mysql
    env_file: ./.env
    volumes:
      - sql-data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    env_file: ./.env
    ports:
      - 8080:80

volumes:
  sql-data: