FROM python:3.12

ARG ID=1000
ARG NAME=dev

RUN groupadd -g $ID $NAME && \
    useradd -m -u $ID -g $ID $NAME
WORKDIR /usr/src/app
RUN pip install flask Flask-MySQLdb uwsgi
USER $NAME
CMD sleep 3 && python app.py